name = "spendrule-dev"
main = "index.ts"
compatibility_date = "2024-01-01"

# R2 Buckets
[[r2_buckets]]
binding = "secure-uploads"
bucket_name = "secure-uploads-preview"
preview_bucket_name = "secure-uploads-preview"

# Environment variables
[vars]
SPENDRULE_MODE = "true"
DEFAULT_BUCKET = "secure-uploads"
CLAUDE_API_KEY = "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"

# Build configuration
[build]
command = "echo 'API-only worker - no dashboard build needed'"