# SpendRule Document Management System Configuration
# Based on R2-Explorer framework

name = "spendrule-doc-upload-dashboard"
main = "packages/worker/dev/index.ts"
compatibility_date = "2024-11-01"

# AI Binding - Cloudflare Workers AI
[ai]
binding = "AI"

# SpendRule R2 bucket binding
[[r2_buckets]]
binding = "secure-uploads"
bucket_name = "secure-uploads"
preview_bucket_name = "secure-uploads-preview"

# Environment variables can be set via wrangler secrets
# wrangler secret put BASIC_AUTH_USERS

[vars]
# SpendRule configuration
SPENDRULE_MODE = "true"
DEFAULT_BUCKET = "secure-uploads"

# No assets - dashboard deployed separately on Cloudflare Pages
# Build configuration - API only
[build]
command = "echo 'API-only worker - no dashboard build needed'"
cwd = "."

# Remove environment configs to eliminate warning
# Single production deployment