# SpendRule Document Management System Configuration
# Based on R2-Explorer framework

name = "spendrule-doc-upload-dashboard"
main = "packages/worker/dev/index.ts"
compatibility_date = "2024-11-01"

# SpendRule R2 bucket binding
[[r2_buckets]]
binding = "secure-uploads"
bucket_name = "secure-uploads"
preview_bucket_name = "secure-uploads-preview"

# Environment variables can be set via wrangler secrets
# wrangler secret put BASIC_AUTH_USERS

[vars]
# SpendRule configuration
SPENDRULE_MODE = "true"
DEFAULT_BUCKET = "secure-uploads"

# SpendRule dashboard assets
assets = { directory = "packages/dashboard/dist/spa", binding = "ASSETS", html_handling = "auto-trailing-slash", not_found_handling = "single-page-application" }

# Build configuration  
[build]
command = "pnpm build-dashboard && echo 'Dashboard built successfully'"
cwd = "."

# Development configuration  
[env.dev]
name = "spendrule-doc-upload-dev"
vars = { SPENDRULE_MODE = "true", DEFAULT_BUCKET = "secure-uploads" }

[env.production] 
name = "spendrule-doc-upload-prod"
vars = { SPENDRULE_MODE = "true", DEFAULT_BUCKET = "secure-uploads" }